### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by r9y9** [r9y9/pyopenjtalk#10]
It should be possible to support Windows as well, but I don't have a machine to test. Would be nice if anyone wants to contribute to this.

**Comment by Hiroshiba** [comment]
I tried to build pyopenjtalk in a Windows environment.
I rewrote setup.py and mecab/src/config.h as follows, and was able to synthesize speech without any problems.

setup.py
https://github.com/Hiroshiba/pyopenjtalk/commit/663045732c9e0df7a66891bbfbba8ebc33a70b2f

mecab/src/config.h
`/* #undef HAVE_WINDOWS_H */` to `#define HAVE_WINDOWS_H 1`
`/* #undef VERSION */`to `#define VERSION "1.10"`
`#define HAVE_DIRENT_H 1` to `// #define HAVE_DIRENT_H 1`

I think `setup.py` can be made more stylish by adding the windows flag, but I don't have a good idea for `config.h`.
(Windows does not have cmake, so the following code does not work...)
https://github.com/r9y9/pyopenjtalk/blob/d28b9108b29b857db8efe153ac483efe38afc2a4/setup.py#L49-L55

**Comment by r9y9** [comment]
Thanks for looking into this. A cleaner way is to write a script that generates config.h. i.e. what cmake currently does: https://github.com/r9y9/open_jtalk/blob/22213146d3491d708ec9b827851de8c0bbca29d7/src/CMakeLists.txt#L43-L79.

It would not be that hard technically but I guess we need to write a bunch of python code to handle run-time check property (parsing config.in, checking headers if exist, checking functions available, etc).

The easiest but not perfect way is to include a pre-generated config.h into the repo and use it at the build time. However, I am reluctant to do this as it may not work on other platforms.

**Comment by Hiroshiba** [comment]
I see.
I think it's a smart solution, but it will take some effort.
If that method is implemented, I will try to run it on windows.
Thanks!
