### ISSUE TITLE
pip install failed

### ISSUE THREAD

**Issue by kamo-naoyuki** [r9y9/pyopenjtalk#3]
I tried to install pyopenjtalk from pypi, but got following error:

```bash
% OPEN_JTALK_INSTALL_PREFIX=(...) pip install pyopenjtalk
(...)
    ValueError: 'pyopenjtalk/openjtalk.pyx' doesn't match any files
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

However I tried `python setup.py develop sdist` and I found `pyopenjtalk/openjtalk.pyx` in the generated tgz, so I couldn't understand why it wasn't uploaded. 
Perhaps didn't you upload the latest version to pypi server?

**Comment by r9y9** [comment]
You are right. I wish I did include *.pyx to the distribution, but there's something I missed to do it. Quickly I tried to do `python setup.py develop sdist` in a fresh pyenv but it also didn't work. Perhaps the behavior depends on the version of setuptools, but not sure. I think the safest way to fix this is to explicitly add those files to MANIFEST.in. Will push a fix soon.

**Comment by r9y9** [comment]
v0.0.2 is up on pypi, including the fix for the issue.

**Comment by kamo-naoyuki** [comment]
Thanks!
