### ISSUE TITLE
Install build error

### ISSUE THREAD

**Issue by Yukimoeli** [r9y9/pyopenjtalk#32]
I keep getting this error while trying to install.
When I use pip to install, an error message appears:FileNotFoundError: [WinError 2]
It prompts me that the system cannot find the specified file
The error message comes from subprocess.py, line1420

**Comment by Hamakaze1s** [comment]
I'm having the same issue. How did you solve it?

**Comment by LAWArthur** [comment]
Same issue here on Windows. Could you share how you solved it?

**Comment by xszqxszq** [comment]
@Hamakaze1s @LAWArthur Check whether CMake is installed or not.
