### ISSUE TITLE
Fail to install pyopenjtalk by pip on M1 platform

### ISSUE THREAD

**Issue by AgI-Dev-Official** [r9y9/pyopenjtalk#37]
I keep getting error while trying to install pyopenjtalk to my M1 Mac by the command: `pip install pyopenjtalk`
I think the reason for the error should come from building numpy according to the error log:

        Building wheels for collected packages: numpy  
            Building wheel for numpy (pyproject.toml): started  
            Building wheel for numpy (pyproject.toml): finished with status 'error'  
            error: subprocess-exited-with-error  

The pyopenjtalk may use an older version(numPy 1.19.5) for construction, and it may not support Apple Silicon platform.
Also, I try to edit the .toml file and build this package locally(Method from), it installed successfully. But when I import the package it failed and said the Array API version of numpy is not correct.

        RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf

However, when I used the command `pip install pyopenjtalk --no-use-pep517` , everything's goes well.
I would like to know where exactly the problem is and if it can be fixed.

OS: macOS Monterey 12.3.1 with M1 Max
Python Version: 3.10.3
Openjtalk version: 0.2.0
numpy version: 1.22.4
Cython version: 0.29.32
Python and all required site-packages is Arm-64 version

**Comment by r9y9** [comment]
https://github.com/r9y9/pyopenjtalk/releases/tag/v0.3.0 the latest release should be compatible with newer versions of numpy. Can you try the latest version?

**Comment by AgI-Dev-Official** [comment]
> https://github.com/r9y9/pyopenjtalk/releases/tag/v0.3.0 the latest release should be compatible with newer versions of numpy. Can you try the latest version?

Thank for your response. The latest version works fine!
