### ISSUE TITLE
Building source code from pypi fails with python3.11.

### ISSUE THREAD

**Issue by sabonerune** [r9y9/pyopenjtalk#52]
I don't think it's officially supported yet.
The reason I opened this issue is that if I install from git it succeeds.

``` shell
# Failed
pip install pyopenjtalk
```
```
# Success
pip install git+https://github.com/r9y9/pyopenjtalk.git@v0.3.0
```

Probably because the generated code in the sdist was not compatible for Python3.11.
I think the next release should include code generated by a newer version of Cython in sdist.

note:
Maybe sdist shouldn't contain generated code.
- cython/cython/issues/5089

**Comment by ZYD20200827** [comment]
![屏幕截图 2023-07-09 165305](https://github.com/r9y9/pyopenjtalk/assets/110762632/07a9a4ec-dfb6-459d-acc8-211ace517378)
但是
![image](https://github.com/r9y9/pyopenjtalk/assets/110762632/927dc330-828d-403f-bcff-2f5b54e9a84f)
(小白)

**Comment by sabonerune** [comment]
`FileNotFoundError: [WinError 2]` may be caused by the build tools not being properly prepared.
On Windows need to install MSVC and CMake and set the appropriate environment variables.

ref: https://learn.microsoft.com/cpp/build/building-on-the-command-line#path_and_environment

And I think `exit code : 128` is an error by git.
