### ISSUE TITLE
subprocess.CalledProcessError: Command '['cmake', '..', '-DHTS_ENGINE_INCLUDE_DIR=.', '-DHTS_ENGINE_LIB=dummy']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by GeekerLeone** [r9y9/pyopenjtalk#62]
setup.py:26: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  _CYTHON_INSTALLED = ver >= LooseVersion(min_cython_ver)
CMake Warning:
  Ignoring extra path from command line:

   ".."

CMake Error: The source directory "G:/Project/VITS/pyopenjtalk-master/pyopenjtalk-master/lib/open_jtalk/src" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
Traceback (most recent call last):
  File "setup.py", line 154, in <module>
    r.check_returncode()
  File "C:\Users\Admin\anaconda3\envs\VITS\lib\subprocess.py", line 448, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['cmake', '..', '-DHTS_ENGINE_INCLUDE_DIR=.', '-DHTS_ENGINE_LIB=dummy']' returned non-zero exit status 1.

cmake version 3.26.4-msvc4
Cython version 3.0.0

**Comment by r9y9** [comment]
Please run `pip install pyopenjtalk`

**Comment by GeekerLeone** [comment]
I did. But it threw me the same issue. I tried to pip install pyopenjtalk with Python 3.11, 3.8, 3.7, 3.6. Also tried to upgrade setuptools. No idea how to do it further. I was stuck with this for a week.
