### ISSUE TITLE
Support for MSVC 14.37 specification changes

### ISSUE THREAD

**Issue by My-MC** [r9y9/pyopenjtalk#69]
### 概要

日本語のほうが正確にお伝えできると思いますので、日本語で書かせていただきます。

MSVC 14.37において仕様変更が行われたらしく、`open_jtalk`の`src/mecab/src/dictionary.cpp`で使われている`std::binary_function`が`functional`に含まれているが読み込まれないため、そのままpyopenjtalkをインストールをするとcl.exeがexit code2でエラーを出しインストールができません。またこの仕様変更よって起こったエラーについて[コミュニティ](https://learn.microsoft.com/en-us/answers/questions/1348183/std-binary-function-is-missing-in-msvc-14-37-32822)でも上がっています。

これはアップデートによって影響範囲は広がっていくと考えられるため早急な修正が必要です。

また`#include <functional>`で検索をかけた感じだと`src\mecab\src\learner_tagger.cpp`にincludeされているだけで、さすがにヘッダーには含まれてませんでした。そして、Linux環境（Ubuntu Focal gcc9.4.0）で`#include <functional>`をすべて削除してもビルドできたことから、僕の知識不足かもしれませんが、以前のMSVCやgccなどはは暗黙的になぜか`functional`を読み込んでいて、ビルドができていたと考えます。

この修正PRはすぐに送ることができます。

### 再現手順

1. MSVC 14.37に更新する（ダウングレードできないので注意してください。）
2. `pyopenjtalk`を再インストールする

<details><summary>English with DeepL</summary>

### Outline

I am writing this in Japanese because I think it is more accurate in Japanese.

The `std::binary_function` used in `src/mecab/src/dictionary.cpp` of `open_jtalk` is included in `functional`, but is not loaded, If you install pyopenjtalk as it is, cl.exe throws an error with exit code2 and cannot install. Also, please contact [community](https://learn.microsoft.com/en-us/answers/questions/1348183/std-binary-function-is-missing-in-msvc-14-37-32822).

This is a problem that needs to be fixed as soon as possible, as it is expected to spread through updates.

Also, I searched for `#include <functional>` and found that it is only included in `src\mecab\src\learner_tagger.cpp`, not in the header as expected. And since I was able to build even after removing all `#include <functional>` in Linux environment (Ubuntu Focal gcc9.4.0), it may be my lack of knowledge, but I think that previous MSVC, gcc, etc. implicitly read `functional` for some reason and were able to build. and it was able to build.

I can send this modified PR immediately.

### Reproduction Procedure

1. update to MSVC 14.37 (note that it cannot be downgraded) 2.
2. reinstall `pyopenjtalk`.

Translated with www.DeepL.com/Translator (free version)
</details>

**Comment by r9y9** [comment]
確認が遅くなりすみません。#include <functional> を当該ソースファイルに追加することになるでしょうか？であれば、良いと思いました。https://learn.microsoft.com/en-us/answers/questions/1348183/std-binary-function-is-missing-in-msvc-14-37-32822 で議論されているように、msvc側のバグっぽい気はしますが、includeを追加すること自体は特に問題ないように思えます。

**Comment by loverubywithout** [comment]
I have same problem when I install pyopenjtalk.

I tried various methods, and in the end, I installed the lower version of msvc in the Visual Studio Installer, and it was successful.

The method of installing the lower version of msvc is to modify the individual components. I installed the msvc 14.34.

**Comment by My-MC** [comment]
返事、PRを出すのが遅くなって申し訳ありません。修正ありがとうございました。
