### ISSUE TITLE
cython compile issue

### ISSUE THREAD

**Issue by dosinsane** [r9y9/pyopenjtalk#70]
i met cython compile issue in pyopenjtalk
i want to know which version of cython can compile pyopenjtalk thanks

**Comment by dosinsane** [comment]
I slove my issue 
cause i have two pc one pc is build successful and another fail
so i try find the reason why I succes my previous pc build 
i find the version of gcc 12.1.0
and cmake 3.27.0
and i don't have cython but i use visual studio 2017 that can compile the pyopenjtalk vers 0.3.2
but unfortunately I don't know the reason if someone can tell me why that will be very helpful thanks

**Comment by ctimict** [comment]
Thank you very much, i spent more than 1 day struggling with pyopenjtalk, i got error when using visual studio 2022.
When I read your article, I uninstalled visual studio 2022 and installed visual studio 2017. and I successfully installed pyopenjtalk.
God bless you !

**Comment by Spr-Aachen** [comment]
Wait, visual studio 2017 can save this? God bless you bro!!!

**Comment by IamMagicSu** [comment]
The 2017 version actually works!!! Thank you so much!!! It wasted so much of my time before..
