### ISSUE TITLE
Command '['cmake', '..', '-DHTS_ENGINE_INCLUDE_DIR=.', '-DHTS_ENGINE_LIB=dummy']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by canbefree** [r9y9/pyopenjtalk#79]
#62  ?    why this  isue  closed?  Can't  find way to solve this  peoblem;  

`pip install pyopenjtalk` not work for me.

Is cmake version peoblem ? 

cmake version 3.29.3
pyton version：3.9

proc/version

Linux version 5.15.133.1-microsoft-standard-WSL2 (root@1c602f52c2e4) (gcc (GCC) 11.2.0, GNU ld (GNU Binutils) 2.37) #1 SMP Thu Oct 5 21:02:42 UTC 2023

**Comment by canbefree** [comment]
peoblem solved~!

don't  use `conda  install cmake`, the correct way is use apt install cmake

**Comment by hancelChiu** [comment]
how to resolve in windows
